# Generated by Django 6.0.1 on 2026-01-15 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='boletas/%Y/%m/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('rut_emisor', models.CharField(blank=True, max_length=20, null=True)),
                ('folio', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('monto_total', models.IntegerField(default=0)),
                ('procesado_exitosamente', models.BooleanField(default=False)),
                ('nota_error', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gastos.obra')),
            ],
        ),
    ]
