# Generated by Django 6.0.1 on 2026-01-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='imagen',
            field=models.FileField(upload_to='boletas/', verbose_name='Boleta o Factura'),
        ),
    ]
