# Generated by Django 6.0.1 on 2026-01-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_alter_gasto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('MATERIALES', 'Materiales de Construcción'), ('MANO_OBRA', 'Mano de Obra / Tratos'), ('MAQUINARIA', 'Arriendo Maquinaria/Combustible'), ('ALIMENTACION', 'Colaciones y Comida'), ('OFICINA', 'Gastos de Oficina/Legal'), ('OTROS', 'Otros Gastos')], default='MATERIALES', max_length=20, verbose_name='Categoría del Gasto'),
        ),
    ]
