# Generated by Django 6.0.1 on 2026-01-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_gasto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción / Detalle'),
        ),
    ]
