# Generated by Django 6.0.1 on 2026-01-21 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_empresa_gasto_empresa_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='direccion',
        ),
        migrations.AddField(
            model_name='obra',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obra',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gastos.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obra',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación/Dirección'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Proyecto'),
        ),
    ]
