# Generated by Django 6.0.1 on 2026-01-21 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0006_remove_obra_direccion_obra_created_at_obra_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('MATERIALES', 'Materiales de Construcción'), ('MANO_OBRA', 'Mano de Obra / Tratos'), ('MAQUINARIA', 'Arriendo Maquinaria'), ('HERRAMIENTAS', 'Herramientas'), ('COMBUSTIBLE', 'Combustible'), ('TRANSPORTE', 'Fletes y Transporte'), ('ALIMENTACION', 'Alimentación'), ('EPP', 'Implementos de Seguridad (EPP)'), ('OFICINA', 'Gastos de Oficina'), ('OTROS', 'Otros Gastos')], default='MATERIALES', max_length=20, verbose_name='Categoría del Gasto'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gastos.obra', verbose_name='Proyecto / Obra'),
        ),
    ]
