# Generated by Django 6.0.1 on 2026-01-23 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0007_alter_gasto_categoria_alter_gasto_obra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('MATERIALES', 'Materiales de Construcción'), ('MANO_OBRA', 'Mano de Obra / Tratos'), ('MAQUINARIA', 'Arriendo Maquinaria'), ('HERRAMIENTAS', 'Herramientas'), ('COMBUSTIBLE', 'Combustible'), ('TRANSPORTE', 'Fletes y Transporte'), ('ALIMENTACION', 'Alimentación'), ('EPP', 'Implementos de Seguridad (EPP)'), ('OFICINA', 'Gastos de Oficina'), ('OTROS', 'Otros Gastos')], max_length=20)),
                ('monto', models.IntegerField(default=0, verbose_name='Monto Presupuestado')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='gastos.obra')),
            ],
            options={
                'unique_together': {('obra', 'categoria')},
            },
        ),
    ]
