# Generated by Django 6.0.1 on 2026-05-01 00:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0008_presupuesto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['-fecha_emision', '-id'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.AlterModelOptions(
            name='obra',
            options={'ordering': ['-activo', 'nombre'], 'verbose_name': 'Obra', 'verbose_name_plural': 'Obras'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'verbose_name': 'Presupuesto', 'verbose_name_plural': 'Presupuestos'},
        ),
        migrations.AddField(
            model_name='gasto',
            name='validado_sii',
            field=models.BooleanField(default=False, verbose_name='Validado por SII'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('MATERIALES', 'Materiales de Construcción'), ('MANO_OBRA', 'Mano de Obra / Tratos'), ('MAQUINARIA', 'Arriendo Maquinaria'), ('HERRAMIENTAS', 'Herramientas'), ('COMBUSTIBLE', 'Combustible'), ('TRANSPORTE', 'Fletes y Transporte'), ('ALIMENTACION', 'Alimentación'), ('EPP', 'Implementos de Seguridad (EPP)'), ('OFICINA', 'Gastos de Oficina'), ('OTROS', 'Otros Gastos')], db_index=True, default='MATERIALES', max_length=20, verbose_name='Categoría del Gasto'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha_emision',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='imagen',
            field=models.FileField(upload_to='boletas/%Y/%m/', verbose_name='Boleta o Factura'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='monto_total',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='rut_emisor',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='obra',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='monto',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Presupuestado'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['empresa', '-fecha_emision'], name='gastos_gast_empresa_19f9af_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['obra', '-fecha_emision'], name='gastos_gast_obra_id_9db85e_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['empresa', 'categoria'], name='gastos_gast_empresa_78c4dd_idx'),
        ),
        migrations.AddIndex(
            model_name='obra',
            index=models.Index(fields=['empresa', 'activo'], name='gastos_obra_empresa_fead32_idx'),
        ),
    ]
