# Generated by Django 6.0.1 on 2026-05-01 18:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0009_alter_empresa_options_alter_gasto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='boleta'),
        ),
    ]
