# Generated by Django 6.0.1 on 2026-05-28 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0011_presupuesto_profundo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'verbose_name': 'Presupuesto (legacy)', 'verbose_name_plural': 'Presupuestos (legacy)'},
        ),
        migrations.AlterField(
            model_name='gasto',
            name='monto_total',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto total (con IVA)'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='categoria',
            field=models.CharField(choices=[('MATERIALES', 'Materiales de Construcción'), ('MO_CONTRATA', 'Mano de Obra · Contrata'), ('MO_SUBCONTRATA', 'Mano de Obra · Subcontrata'), ('MO_JORNAL', 'Mano de Obra · Jornal / Día'), ('MO_TRATO', 'Mano de Obra · Trato'), ('MAQUINARIA', 'Arriendo Maquinaria'), ('HERRAMIENTAS', 'Herramientas y Equipos'), ('COMBUSTIBLE', 'Combustible'), ('TRANSPORTE', 'Fletes y Transporte'), ('ALOJAMIENTO', 'Alojamiento / Arriendo'), ('ALIMENTACION', 'Alimentación'), ('VIATICOS', 'Viáticos y Movilización'), ('EPP', 'Implementos de Seguridad (EPP)'), ('OFICINA', 'Gastos de Oficina'), ('OTROS', 'Otros Gastos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='monto',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
