# Generated by Django 6.0.1 on 2026-05-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0012_alter_presupuesto_options_alter_gasto_monto_total_and_more'),
        ('gastos', '0012_curvas_subcontratos_avance'),
    ]

    operations = [
    ]
